### ISSUE TITLE
Support for temporarily publishing to Bintray

### ISSUE THREAD

**Issue by aleksandr-vin** [47degrees/github4s#242]
While I'm developing in a fork, and the process of reviewing/merging/releasing my PR is ongoing, I'd like to temporarily publish my custom version to Bintray.

I've followed https://github.com/sbt/sbt-bintray instructions but still see two issues:
- added `licenses` are ignored (worked around by setting `bintrayOmitLicense := true`)
- still `sbt publish` tries to publish to oss.sonatype.org, ignoring bintray settings.

_build.sbt_ looks complicated and it seems that temporarily added bintray settings are overwritten at the end.

**Comment by BenFradet** [comment]
doesn't seem to be related to this repo per se, closing.
