### ISSUE TITLE
Wrong API endpoint for listUserRepos

### ISSUE THREAD

**Issue by juli1** [47degrees/github4s#255]
In `listUserRepos` the API called is `users/$user/repos`. This seems to be the incorrect endpoint and be `/user/repos`

`listUserRepos` is documented to have a type parameter that can take the values "all", "public", "private",
   "forks", "sources" or "member" which seems to fit more or less with `/user/repos`. On the other hand, `users/$user/repos` does not even has the value `private` or `public` for the type. I guess there is a problem with the API being called.

**Comment by BenFradet** [comment]
The implementation seems to correspond to https://developer.github.com/v3/repos/#list-repositories-for-a-user, feel free to reopen if I'm missing something.
