### ISSUE TITLE
GHException extends Throwable

### ISSUE THREAD

**Issue by dcsobral** [47degrees/github4s#362]
It should really extend `Exception` instead, since it's something applications could possibly handle -- as evidenced by the fact it's returned inside a `Left` instead of being thrown.

**Comment by BenFradet** [comment]
That sounds sensible to me 👍

**Comment by kalexmills** [comment]
On the most recent version, it looks like this is now the case. Does this issue need to be closed?

**Comment by BenFradet** [comment]
mmh it still extends `Throwable`
