### ISSUE TITLE
Shutting down connection pool info messages

### ISSUE THREAD

**Issue by tovbinm** [47degrees/github4s#371]
When using the client the following INFO messages are printed for each API invocation:
```
o.h.c.PoolManager - Shutting down connection pool: curAllocated=1 idleQueues.size=1 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
```
Is this by design? Why shutdown connection pool on each API call?

**Comment by BenFradet** [comment]
This is because the http client we use to make the call is short-lived.
However, I agree we definitely could support two modes of executions:
- the current one with a short-lived client
- a new one which defers the client management to the library user through dependency injection
