### ISSUE TITLE
Support for private GitHub Enterprise installations

### ISSUE THREAD

**Issue by satorg** [47degrees/github4s#379]
The base GitHub API URLs are hard-coded inside the `GithubAPIv3Config` class:
```scala
case class GithubAPIv3Config(
    baseUrl: String = "https://api.github.com/",
    authorizeUrl: String =
      "https://github.com/login/oauth/authorize?client_id=%s&redirect_uri=%s&scope=%s&state=%s",
    accessTokenUrl: String = "https://github.com/login/oauth/access_token"
)
```
which makes impossible to leverage **github4s** in those companies which use their private GitHub installations and obviously different base API URLs.

Currently it seems there's no way to override these URLs.

**Comment by satorg** [comment]
I believe I would be great to allow to override these values or/and read them from system properties and configuration files.

**Comment by BenFradet** [comment]
Definitely agreed 👍

**Comment by BenFradet** [comment]
I think we could turn that case class into an implicit parameter when instantiating `Github[F](client, token)`

**Comment by satorg** [comment]
Agree, I think it could look something like:
```scala
def apply[F[_]: ConcurrentEffect](
      accessToken: Option[String] = None,
      timeout: Option[Duration] = None
  )(implicit ec: ExecutionContext, config = GithubAPIv3Config.default()): Github[F]
```
where `GithubAPIv3Config.default()` creates config for the public GitHub (`https://api.github.com/` etc)
although my concern here is that `GithubAPIv3Config` looks more like implementation details.
WDYT?

**Comment by BenFradet** [comment]
yes I think it needs renaming, maybe something like:

```scala

final case class GithubConfig(
  baseUrl: String = "https://api.github.com/",
  authorizeUrl: String = "https://github.com/login/oauth/authorize?client_id=%s&redirect_uri=%s&scope=%s&state=%s",
  accessTokenUrl: String = "https://github.com/login/oauth/access_token"
)

object GithubConfig {  
  implicit val default: GithubConfig = GithubConfig()
}
```

and then have:

```scala
class Github[F[_]: Sync](
    client: Client[F],
    accessToken: Option[String]
)(implicit ghConfig: GithubConfig)
```

👍

**Comment by satorg** [comment]
@BenFradet, I submitted a PR #384, could you take a look please?
