### ISSUE TITLE
HttpClient should support default headers

### ISSUE THREAD

**Issue by dcsobral** [47degrees/github4s#447]
While looking at github's api docs I noticed that `UserAgent` is mandatory, and quickly verified github4s doesn't add it by default. While http4s has its own default, I decided I wanted to use "github4s" instead. However, I quickly realized that meant adding a header to every github4s call, which is very redundant.

For cases like this and, for that matter, github feature flags, it would be very convenient if `HttpClient` would take default headers.

**Comment by BenFradet** [comment]
created #461 :+1:
