### ISSUE TITLE
Getting NotFound error when using repos.createRelease api

### ISSUE THREAD

**Issue by bilal-fazlani** [47degrees/github4s#524]
When using repos api to create new release, I get NotFound error

```scala
val req = gh.repos.createRelease(
      "bilal-fazlani",
      "test-repo",
      "0.1.0",
      "0.1.0",
      "New features",
      None,
      Some(true),
      Some(false),
      Map.empty
    )
```

Code to run

```scala
    val response = req.unsafeRunSync()

    response.result match {
      case Left(e)  => 
        println(s"Something went wrong: ${e.getMessage}")
        e.printStackTrace
      case Right(r) => 
        println(r)
    }
```

output:

```
NotFoundError(Not Found, https://developer.github.com/v3/repos/releases/#create-a-release)
```

I have tried this for both public and private repose. Not sure what is NotFound

**Comment by fedefernandez** [comment]
@bilal-fazlani the GitHub API sometimes returns a 404 when you don't have permissions for some resource. Could you please double check that you're using a good token?

**Comment by bilal-fazlani** [comment]
Ok sure. I will check with a different token

**Comment by bilal-fazlani** [comment]
Token was the issue. Apologies and thank you for the help.

**Comment by fedefernandez** [comment]
No worries! Glad it was solved 👍
