### ISSUE TITLE
 Receive 422 response when searching Issues

### ISSUE THREAD

**Issue by drwlrsn** [47degrees/github4s#569]
Hi! I am pretty new to Scala so bear with me. I can't really pinpoint what's going wrong, but hopefully I can explain it well enough.

## Version
github4s: v0.26.0

## What I trying to do
I am trying to use the [Issue Search](https://47degrees.github.io/github4s/issue#search-issues) to find Pull Requests in a project, that are open and have a particular label. In the REPL, I've tried:

```scala
client.issues.searchIssues(
	"", 
	List(OwnerParamInRepository("47degrees/github4s"), IssueTypePullRequest, LabelParam("bug"), IssueStateOpen))
.unsafeRunSync()
```
This returns response with a `422` status code:

```
GHResponse(Left(UnprocessableEntityError(Validation Failed, List(UnprocessableEntity(Search,q,InvalidFormatting)))),422, ...)
```

This results in a query string of `+repo:47degrees/github4s+type:pr+label:bug+state:open`. Although it looks a bit odd works fine as an [API request](https://api.github.com/search/issues?q=+repo:47degrees/github4s+type:pr+label:bug+state:open).

I noticed if everything except the `OwnerParamInRepository` the search succeeds just fine.

Running

```scala
client.issues.searchIssues("", List(OwnerParamInRepository("47degrees/github4s"))).unsafeRunSync()
```

Returns a response of

```
github4s.GHResponse[github4s.domain.SearchIssuesResult] = GHResponse(Right(SearchIssuesResult(0,false,List())),200, ...)
```

Thanks for the great work!

**Comment by BenFradet** [comment]
mmh weird, is the leading `+` the issue?

**Comment by drwlrsn** [comment]
The leading `+` seems to be just fine. The following request works fine:

```
https://api.github.com/search/issues?q=+repo:47degrees/github4s+type:pr+label:enhancement+state:open
```

**Comment by drwlrsn** [comment]
Ah okay I think I have some more info. `IssuesInterpreter` assembles a query here:
https://github.com/47degrees/github4s/blob/89323076ff6e81ea5bbfd45e8a3f53c3ba9c41db/github4s/src/main/scala/github4s/interpreters/IssuesInterpreter.scala#L58

At this point the value of the `q` has a string value of: `+repo:7shifts/webapp+type:pr+state:open+label:law+in:title`

I setup `mitmproxy` to check what the actual request looks like, and the request it intercepts looks like this:

```
GET https://140.82.112.6/search/issues?q=%2Brepo%3A7shifts/webapp%2Btype%3Apr%2Bstate%3Aopen%2Blabel%3Alaw%2Bin%3Atitle
```

It seems like percent encoding the `+` and `:` chars is breaking the request

**Comment by BenFradet** [comment]
good catch! :+1:

**Comment by sloshy** [comment]
I believe I've found the source of the issue. Whether or not it's a bug remains to be seen, but it appears that http4s uses different encoder settings for query parameters VS the main URL. I've submitted this to them as the above issue (the second one, the first was a similar issue I thought was related but was a bit different), so hopefully we will hear back soon!

**Comment by sloshy** [comment]
Fix is posted above ^
