### ISSUE TITLE
Ignore the reviewers test

### ISSUE THREAD

**Issue by BenFradet** [47degrees/github4s#586]
The reviewers test needs admin scope to succeed and the ci token doesn't seem to have it: https://github.com/47degrees/github4s/runs/1530047606?check_suite_focus=true#step:11:577

**Comment by sloshy** [comment]
I have a fix up for this, but it looks like there is another failing test. I'm not very familiar with the github API so I'm not sure what the issue could be, so I'll mark it as WIP/Draft for now until someone else can look at it.
