### ISSUE TITLE
Repository doesn't contain a parent

### ISSUE THREAD

**Issue by tdudzik** [47degrees/github4s#603]
I was trying to use github4s for a project I'm working on but wasn't able to because `Repository` doesn't seem to contain a parent even though it contains e.g. owner and organization (https://github.com/47degrees/github4s/blob/master/github4s/src/main/scala/github4s/domain/Repository.scala). Is there a specific reason for it? Could it be added?

**Comment by BenFradet** [comment]
yes, it is possible to add it :+1:
