### ISSUE TITLE
ScalaJS artifacts for Scala 2.13 and Scala 3

### ISSUE THREAD

**Issue by vincenzobaz** [47degrees/github4s#701]
I cannot find scalajs artifacts for Scala 2.13 and Scala 3:

```
➜  myproject cs complete com.47deg:github4s_sjs
github4s_sjs0.6_2.10
github4s_sjs0.6_2.11
github4s_sjs0.6_2.12
```

**Comment by fedefernandez** [comment]
Hi @vincenzobaz, ScalaJS support was removed on version [v0.21.0](https://github.com/47degrees/github4s/releases/tag/v0.21.0)

**Comment by vincenzobaz** [comment]
Was a dependency not available?

**Comment by fedefernandez** [comment]
@vincenzobaz yeah, IIRC `http4s` didn't have ScalaJS support when we migrated from `rosshttp`. I think that now it's supported so maybe it'd make sense to add support again.

**Comment by vincenzobaz** [comment]
Thank you for the info @fedefernandez !
