### ISSUE TITLE
patch field being String in FileComparison causing compareCommit to crash

### ISSUE THREAD

**Issue by rojsrojs** [47degrees/github4s#746]
If the difference between two commits contains file difference that is only a rename (rename of file or moving file to another location), `patch` does not exist and therefore the parsing of the json fails. Instead `previous_filename` exists to indicate what name the file had before. This bug can easily be resolved by changing the type of patch to Option[String].

![image](https://user-images.githubusercontent.com/25762875/148947205-d52cd23c-6a55-471d-8938-ec47ba893ed1.png)

**Comment by fedefernandez** [comment]
Thanks @rojsrojs
