### ISSUE TITLE
bad documentation URL in github enterprise 

### ISSUE THREAD

**Issue by TomyMeren** [47degrees/github4s#871]
I'm trying to publish a microsite in a Github Enterprise repo and when I call the method https://github.com/47degrees/github4s/blob/9c18225cc61f756aace9ddcb5d134720c882edb0/github4s/shared/src/main/scala/github4s/algebras/GitData.scala#L42 I get the following error:
`Caused by: NotFoundError(Not Found, https://docs.github.com/enterprise/3.4/rest)
`
Should update to `https://docs.github.com/en/enterprise-server@3.4/rest`

**Comment by fedefernandez** [comment]
That URI is coming directly from the GitHub API response.
